### ISSUE TITLE
Components in META-INF/faces-config.xml

### ISSUE THREAD

**Issue by pkral3** [rollinhand/c3faces#1]
Hello, for the spring-boot with primefaces pls. add the components to the faces-config.xml also

	<component>
		  <component-type>org.kivio.c3faces.component.Area</component-type>
		  <component-class>org.kivio.c3faces.component.Area</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.AreaSpline</component-type>
		  <component-class>org.kivio.c3faces.component.AreaSpline</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.AreaStep</component-type>
		  <component-class>org.kivio.c3faces.component.AreaStep</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.Bar</component-type>
		  <component-class>org.kivio.c3faces.component.Bar</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.C3Chart</component-type>
		  <component-class>org.kivio.c3faces.component.C3Chart</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.ComponentProperties</component-type>
		  <component-class>org.kivio.c3faces.component.ComponentProperties</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.Donut</component-type>
		  <component-class>org.kivio.c3faces.component.Donut</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.Gauge</component-type>
		  <component-class>org.kivio.c3faces.component.Gauge</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.Line</component-type>
		  <component-class>org.kivio.c3faces.component.Line</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.Pie</component-type>
		  <component-class>org.kivio.c3faces.component.Pie</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.Scatter</component-type>
		  <component-class>org.kivio.c3faces.component.Scatter</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.Spline</component-type>
		  <component-class>org.kivio.c3faces.component.Spline</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.Step</component-type>
		  <component-class>org.kivio.c3faces.component.Step</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.AreaProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.AreaProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.AxesProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.AxesProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.AxisProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.AxisProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.AxisXProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.AxisXProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.AxisYProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.AxisYProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.BarProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.BarProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.C3Property</component-type>
		  <component-class>org.kivio.c3faces.component.property.C3Property</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.DonutProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.DonutProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.GaugeProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.GaugeProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.GridProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.GridProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.GridsProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.GridsProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.GridXProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.GridXProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.GridYProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.GridYProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.LegendProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.LegendProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.PaddingProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.PaddingProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.PieProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.PieProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.PointProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.PointProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.RegionProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.RegionProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.RegionsProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.RegionsProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.SizeProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.SizeProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.SubchartProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.SubchartProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.TooltipProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.TooltipProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.TransitionProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.TransitionProperty</component-class>
	</component>
	<component>
		  <component-type>org.kivio.c3faces.component.property.ZoomProperty</component-type>
		  <component-class>org.kivio.c3faces.component.property.ZoomProperty</component-class>
	</component>

Thanks! pk

**Comment by rollinhand** [comment]
There was an update to C3Faces. It will be soon available as version 1.3 from Maven central.
